#!/usr/bin/env node
/**
 * Types-sync CLI.
 *
 * Subcommands:
 *   capture   Boot/use a running WC instance, fetch the discovery JSON for
 *             admin/store/analytics, and write a normalised snapshot to
 *             scripts/types-sync/snapshots/wc-<version>.json.
 *
 *   check     Load the most recent (or specified) snapshot, introspect every
 *             Zod schema in schema-map.ts, run the diff engine, and write
 *             scripts/types-sync/out/drift.{json,md}. Exits 1 if any `error`
 *             severity rows exist (unless --allow-warn is passed).
 *
 *   list-routes   Dump unmapped routes from the snapshot (helps grow the
 *                 registry).
 *
 * Flags:
 *   --base-url <url>      WP base URL (default: http://localhost:8080)
 *   --wc-version <ver>    WC version label for the snapshot file
 *   --snapshot <path>     Override snapshot path on `check`
 *   --allow-warn          Treat warns as non-fatal (errors still fail)
 *   --json                Emit JSON to stdout instead of writing files (check)
 */

import { readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { execSync } from 'node:child_process';

import { createJiti } from 'jiti';

import { captureUpstream } from './capture-upstream.mjs';
import { introspectZodSchema } from './introspect-zod.mjs';
import { diffPair, summarise } from './diff.mjs';
import { writeJson, writeMarkdown, assignDriftIds } from './report.mjs';
import { sortKeysDeep } from './normalise.mjs';
import { buildSdkSourceIndex } from './sdk-source-index.mjs';
import { reconcileAcrossVersions } from './reconcile.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const SNAPSHOTS_DIR = join(HERE, 'snapshots');
const OUT_DIR = join(HERE, 'out');
const SUPPORT_WINDOW_PATH = join(HERE, 'support-window.json');

function parseArgs(argv) {
  const args = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const key = a.slice(2);
      const next = argv[i + 1];
      if (next && !next.startsWith('--')) {
        args[key] = next;
        i++;
      } else {
        args[key] = true;
      }
    } else {
      args._.push(a);
    }
  }
  return args;
}

async function loadRegistry() {
  const jiti = createJiti(import.meta.url, {
    interopDefault: true,
    moduleCache: false,
  });
  const mod = await jiti.import(resolve(HERE, 'schema-map.ts'));
  if (!Array.isArray(mod.SCHEMA_MAP)) {
    throw new Error(
      'schema-map.ts did not export SCHEMA_MAP as an array — registry not loaded'
    );
  }
  return mod.SCHEMA_MAP;
}

function findLatestSnapshot() {
  try {
    const files = readdirSync(SNAPSHOTS_DIR).filter(
      (f) => f.startsWith('wc-') && f.endsWith('.json')
    );
    if (files.length === 0) return null;
    files.sort();
    return join(SNAPSHOTS_DIR, files[files.length - 1]);
  } catch {
    return null;
  }
}

function autoLoadLocalCreds() {
  // For local docker runs we look for the WP admin app password generated by
  // `pnpm wp:env:up`. It works as Basic auth (username + app password), so we
  // pass it as consumerKey/consumerSecret to the capture script.
  try {
    const file = resolve(
      HERE,
      '..',
      '..',
      'infra',
      'wordpress',
      'scripts',
      'generated-app-passwords.txt'
    );
    const text = readFileSync(file, 'utf8');
    const m = text.match(/WP_ADMIN_APP_PASSWORD=([^\s#]+)/);
    if (!m) return null;
    const user = process.env.WP_ADMIN_USER ?? 'admin';
    return { consumerKey: user, consumerSecret: m[1] };
  } catch {
    return null;
  }
}

async function runCapture(args) {
  const baseUrl = args['base-url'] ?? 'http://localhost:8080';
  const wcVersion = args['wc-version'] ?? process.env.WC_VERSION ?? 'unknown';
  let creds = {
    consumerKey: process.env.WP_CONSUMER_KEY,
    consumerSecret: process.env.WP_CONSUMER_SECRET,
  };
  if (!creds.consumerKey || !creds.consumerSecret) {
    const local = autoLoadLocalCreds();
    if (local) {
      creds = local;
      console.log(
        `[capture] using local WP admin app password as ${creds.consumerKey}`
      );
    }
  }

  console.log(`[capture] base=${baseUrl} wc=${wcVersion}`);
  const snapshot = await captureUpstream({
    baseUrl,
    wcVersion,
    creds,
    log: (msg) => console.log(msg),
  });

  mkdirSync(SNAPSHOTS_DIR, { recursive: true });
  const out = join(SNAPSHOTS_DIR, `wc-${wcVersion}.json`);
  writeFileSync(out, JSON.stringify(snapshot, null, 2) + '\n', 'utf8');
  console.log(`[capture] wrote ${out}`);
}

function gitSdkRef() {
  try {
    return execSync('git rev-parse --short HEAD', {
      cwd: resolve(HERE, '..', '..'),
      stdio: ['ignore', 'pipe', 'ignore'],
    })
      .toString()
      .trim();
  } catch {
    return 'unknown';
  }
}

/**
 * Load support-window.json. Returns null if absent, indicating the caller
 * should fall back to single-snapshot behaviour. Validates the invariant
 * that `latest` ∈ `versions[]`.
 */
function loadSupportWindow() {
  try {
    const raw = JSON.parse(readFileSync(SUPPORT_WINDOW_PATH, 'utf8'));
    if (!Array.isArray(raw.versions) || raw.versions.length === 0) {
      throw new Error('support-window.json: `versions` must be a non-empty array');
    }
    if (typeof raw.latest !== 'string' || !raw.versions.includes(raw.latest)) {
      throw new Error(
        `support-window.json: \`latest\` (${raw.latest}) must be one of \`versions\` (${raw.versions.join(', ')})`
      );
    }
    return raw;
  } catch (err) {
    if (err.code === 'ENOENT') return null;
    throw err;
  }
}

/**
 * Diff one registry entry against one snapshot. Returns the drift records.
 * Pure function — does not mutate inputs. Used by both single-version and
 * multi-version paths so the per-entry resolution logic stays in one place.
 */
function diffEntryAgainstSnapshot(entry, snapshot, options) {
  const drifts = [];
  const upstreamRoute = snapshot.surfaces?.[entry.surface]?.[entry.route];
  if (!upstreamRoute) {
    drifts.push({
      surface: entry.surface,
      route: entry.route,
      kind: entry.kind,
      field: '<route>',
      driftKind: 'route-missing-upstream',
      severity: 'error',
      sdk: { name: entry.name },
      upstream: null,
    });
    return drifts;
  }

  let upstream = null;
  if (entry.kind === 'response') {
    upstream = upstreamRoute.response;
  } else if (entry.kind === 'request') {
    upstream =
      upstreamRoute.request?.[entry.method ?? 'POST'] ??
      upstreamRoute.request?.PUT ??
      upstreamRoute.request?.PATCH ??
      null;
  } else if (entry.kind === 'query') {
    upstream = upstreamRoute.query?.[entry.method ?? 'GET'] ?? null;
  }

  if (!upstream) {
    drifts.push({
      surface: entry.surface,
      route: entry.route,
      kind: entry.kind,
      field: '<endpoint>',
      driftKind: 'endpoint-missing-upstream',
      severity: 'warn',
      sdk: { name: entry.name, method: entry.method ?? null },
      upstream: null,
    });
    return drifts;
  }

  let sdk;
  try {
    sdk = introspectZodSchema(entry.zod, entry.kind);
  } catch (err) {
    drifts.push({
      surface: entry.surface,
      route: entry.route,
      kind: entry.kind,
      field: '<introspection>',
      driftKind: 'zod-introspection-failed',
      severity: 'error',
      sdk: { name: entry.name, error: String(err?.message ?? err) },
      upstream: null,
    });
    return drifts;
  }

  const isLoose = sdk.additionalProperties === true;
  return diffPair({
    sdk,
    upstream,
    surface: entry.surface,
    route: entry.route,
    kind: entry.kind,
    isLoose,
    options,
  });
}

async function runCheck(args) {
  // Description drift comparison defaults ON. Pass --no-check-descriptions
  // to silence it (e.g. while migrating JSDoc → .describe() and the noise
  // would bury real drift).
  const checkDescriptions = args['no-check-descriptions'] !== true;
  const diffOptions = { checkDescriptions };

  const window = loadSupportWindow();
  // --snapshot or --wc-version explicitly forces single-version mode (handy
  // for `pnpm types:sync:local` and ad-hoc checks against a specific file).
  const explicitSingle = Boolean(args.snapshot || args['wc-version']);
  const useWindow =
    !explicitSingle && window != null && window.versions.length > 1;

  let snapshotPath; // path of the latest/anchor snapshot for meta info
  let drifts;

  const registry = await loadRegistry();

  if (useWindow) {
    console.log(
      `[check] support window: ${window.versions.join(', ')} (latest=${window.latest})`
    );

    /** @type {Map<string, object>} version → snapshot */
    const snapshots = new Map();
    for (const v of window.versions) {
      const p = join(SNAPSHOTS_DIR, `wc-${v}.json`);
      try {
        snapshots.set(v, JSON.parse(readFileSync(p, 'utf8')));
      } catch (err) {
        console.error(
          `[check] missing snapshot for version ${v} at ${p}: ${err.message}`
        );
        process.exit(2);
      }
    }
    snapshotPath = join(SNAPSHOTS_DIR, `wc-${window.latest}.json`);

    drifts = [];
    for (const entry of registry) {
      // Diff against every supported version, then reconcile.
      /** @type {Map<string, object[]>} */
      const perVersion = new Map();
      for (const [v, snap] of snapshots) {
        perVersion.set(v, diffEntryAgainstSnapshot(entry, snap, diffOptions));
      }
      const reconciled = reconcileAcrossVersions({
        perVersionDrifts: perVersion,
        window,
        registryEntry: entry,
      });
      drifts.push(...reconciled);
    }
  } else {
    // Single-version path — preserves the original behaviour byte-for-byte
    // when there's no window (or window has only one entry).
    snapshotPath =
      args.snapshot ??
      (args['wc-version']
        ? join(SNAPSHOTS_DIR, `wc-${args['wc-version']}.json`)
        : window
          ? join(SNAPSHOTS_DIR, `wc-${window.latest}.json`)
          : findLatestSnapshot());

    if (!snapshotPath) {
      console.error(
        `[check] No snapshot found in ${SNAPSHOTS_DIR}. Run \`pnpm types:sync:capture\` first.`
      );
      process.exit(2);
    }

    if (window?.versions.length === 1) {
      console.log(
        `[check] single-version mode (window has 1 entry: ${window.latest})`
      );
    } else if (explicitSingle && window) {
      console.log(
        '[check] single-version mode forced by --snapshot/--wc-version (back-compat checks skipped)'
      );
    }

    const snapshot = JSON.parse(readFileSync(snapshotPath, 'utf8'));
    const singleVersion = snapshot.wcVersion ?? 'unknown';
    const fakeWindow = { versions: [singleVersion], latest: singleVersion };
    drifts = [];
    for (const entry of registry) {
      const raw = diffEntryAgainstSnapshot(entry, snapshot, diffOptions);
      // Run the reconciler with a one-element window so deprecation acks
      // are honoured even in single-version mode (no other rules fire when
      // there are no older versions).
      const reconciled = reconcileAcrossVersions({
        perVersionDrifts: new Map([[singleVersion, raw]]),
        window: fakeWindow,
        registryEntry: entry,
      });
      drifts.push(...reconciled);
    }
  }

  // Read the latest snapshot for capturedAt/version metadata. We re-read here
  // (cheap) rather than thread the snapshot object through both code paths.
  const latestSnapshot = JSON.parse(readFileSync(snapshotPath, 'utf8'));
  const meta = {
    wcVersion: latestSnapshot.wcVersion,
    capturedAt: latestSnapshot.capturedAt,
    sdkRef: gitSdkRef(),
    generatedAt: new Date().toISOString(),
    snapshot: snapshotPath,
    registrySize: registry.length,
    supportWindow: useWindow ? window : undefined,
  };

  // Assign per-severity sequential ids (ERROR-001, WARN-001, INFO-001) so
  // every row has a stable handle that's easy to reference in PR comments
  // and follow-up issues.
  assignDriftIds(drifts);

  // Resolve "surface|route" → SDK source file so the markdown report can
  // link straight to the schema. Picks the file of the first registry entry
  // that maps to the route (the trio usually lives in one file).
  const repoRoot = resolve(HERE, '..', '..');
  const sourceIndex = buildSdkSourceIndex(repoRoot);
  const routeFiles = {};
  for (const entry of registry) {
    const key = `${entry.surface}|${entry.route}`;
    if (routeFiles[key]) continue;
    const file = sourceIndex.get(entry.name);
    if (file) routeFiles[key] = file;
  }

  if (args.json) {
    process.stdout.write(
      JSON.stringify(sortKeysDeep({ meta, drifts }), null, 2) + '\n'
    );
  } else {
    mkdirSync(OUT_DIR, { recursive: true });
    writeJson(join(OUT_DIR, 'drift.json'), drifts, meta);
    writeMarkdown(join(OUT_DIR, 'drift.md'), drifts, meta, { routeFiles });
    console.log(`[check] wrote ${join(OUT_DIR, 'drift.json')}`);
    console.log(`[check] wrote ${join(OUT_DIR, 'drift.md')}`);
  }

  const counts = summarise(drifts);
  console.error(
    `[check] ${counts.error ?? 0} error / ${counts.warn ?? 0} warn / ${
      counts.info ?? 0
    } info (registry=${registry.length})`
  );

  // Errors always fail CI. Warns are signal but non-fatal by default; pass
  // --strict to fail on warns too.
  const failOnWarn = args.strict === true;
  if ((counts.error ?? 0) > 0) process.exit(1);
  if (failOnWarn && (counts.warn ?? 0) > 0) process.exit(1);
}

/**
 * Print the support-window versions to stdout, one per line. Used by CI
 * (and any wrapper script) to drive a docker-boot loop without parsing JSON.
 */
function runWindowList() {
  const window = loadSupportWindow();
  if (!window) {
    console.error('[window] no support-window.json');
    process.exit(2);
  }
  for (const v of window.versions) process.stdout.write(v + '\n');
}

/**
 * Capture every version listed in support-window.json. Does NOT manage
 * docker — caller (CI matrix or wrapper script) is responsible for booting
 * the right WC version before each iteration.
 *
 * Flags `--base-url` and creds are passed through. The current docker boot
 * is assumed to match `args.wc-version` if supplied; otherwise we iterate
 * the whole window (rare local use case — usually CI does this in matrix).
 */
async function runCaptureWindow(args) {
  const window = loadSupportWindow();
  if (!window) {
    console.error('[capture-window] no support-window.json');
    process.exit(2);
  }
  const only = args['wc-version'];
  const versions = only ? [only] : window.versions;
  for (const v of versions) {
    if (!window.versions.includes(v)) {
      console.error(
        `[capture-window] ${v} is not in support-window.json (${window.versions.join(', ')})`
      );
      process.exit(2);
    }
    console.log(`[capture-window] === ${v} ===`);
    await runCapture({ ...args, 'wc-version': v });
  }
}

async function runListRoutes(args) {
  const snapshotPath =
    args.snapshot ??
    (args['wc-version']
      ? join(SNAPSHOTS_DIR, `wc-${args['wc-version']}.json`)
      : findLatestSnapshot());
  if (!snapshotPath) {
    console.error('[list-routes] no snapshot');
    process.exit(2);
  }
  const snapshot = JSON.parse(readFileSync(snapshotPath, 'utf8'));
  const registry = await loadRegistry();
  const mapped = new Set(registry.map((e) => `${e.surface} ${e.route}`));
  const lines = [];
  for (const surface of Object.keys(snapshot.surfaces ?? {}).sort()) {
    for (const route of Object.keys(snapshot.surfaces[surface]).sort()) {
      const key = `${surface} ${route}`;
      if (!mapped.has(key)) lines.push(key);
    }
  }
  process.stdout.write(lines.join('\n') + '\n');
  console.error(`[list-routes] ${lines.length} unmapped`);
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const cmd = args._[0];
  switch (cmd) {
    case 'capture':
      await runCapture(args);
      break;
    case 'capture-window':
      await runCaptureWindow(args);
      break;
    case 'check':
      await runCheck(args);
      break;
    case 'list-routes':
      await runListRoutes(args);
      break;
    case 'window-versions':
      runWindowList();
      break;
    default:
      console.error(
        'Usage: cli.mjs <capture|capture-window|check|list-routes|window-versions> [flags]'
      );
      process.exit(2);
  }
}

main().catch((err) => {
  console.error(err?.stack ?? err);
  process.exit(1);
});
