packages:
  - packages/*
  - apps/*

ignoredBuiltDependencies:
  - '@clerk/shared'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@swc/core'
  - esbuild
  - lmdb
  - msgpackr-extract
  - nx
  - unrs-resolver
